### PR TITLE
Fix Failing Build in New Repo

### PR DESCRIPTION
**Pull request by patricktnast**
### Description

- *Category*: other/misc
- *JIRA issue*: [MIC-4100](https://jira.ihme.washington.edu/browse/MIC-4100)
- *Research reference*: More of an "Engineering" reference, but:  [Repository Creation Doc](https://ihmeuw.github.io/vivarium_development/docs/build/html/process_tutorials/new_research_repo.html)

### Changes and notes
The build for the template-made repository was failing for:

-  including (no longer supported) Python 3.6 builds
- using an out-of-date `black` version
- a number of linting / import sorting issues

I amended the build configuration and ran `black`/`isort` so the CI would pass.

### Verification and Testing
CI Passing

### CODE REVIEW

**Comment by ramittal** [comment]
Seems most of the changes are from ' to ". Is there a team standard or setting that we all should use to avoid? If " is the standard, it would be great to have a PR just changing from ' to " and separate other changes to another PR.

**Comment by mattkappel** [comment]
@ramittal Our team standard is what `black` does. Our use of `black` came after most of the development on the template. We ought to carry these linting changes to the template. Using `black` directly on the template is problematic since there's the cookie cutter markup invalidating the Python.

**Comment by ramittal** [comment]
@mattkappel Thanks for the background. I would suggest to make these minor changes to template to keep the new repos that will be created clean from get go. Now based on this PR, I believe the changes can be applied manually to template.

**Comment by mattkappel** [comment]
@ramittal Totally agree. I created [MIC-4119](https://jira.ihme.washington.edu/browse/MIC-4119) for this.

**Review by stevebachmeier — APPROVED** [review]

**Pull request merged**
